contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: d702f63a-a525-4139-8031-9f79abb651df
inputs:
- description: 'each alert in cortex xdr case '
  key: alert
  playbookInputQuery: null
  required: true
  value:
    complex:
      accessor: alerts
      root: PaloAltoNetworksXDR.Incident.[0]
- description: ""
  key: incident_id
  playbookInputQuery: null
  required: false
  value:
    simple: PaloAltoNetworksXDR.Incident.incident_id
name: Scenario
outputs:
- contextPath: Match
  description: match
  type: unknown
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ea7962db-48e7-42d1-8c29-fa6d70a7223d
      iscommand: false
      name: ""
      version: -1
    taskid: ea7962db-48e7-42d1-8c29-fa6d70a7223d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 235,
          "y": 65
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.alert.source
          operator: isEqualString
          right:
            value:
              simple: XDR Agent
      - - left:
            iscontext: true
            value:
              simple: inputs.alerts.host_ip
          operator: in
          right:
            value:
              simple: list.authorizedhost
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7a72f385-0e5c-4fd9-8568-61c8b1ff3b7b
      iscommand: false
      name: 'Scenario Match? '
      type: condition
      version: -1
    taskid: 7a72f385-0e5c-4fd9-8568-61c8b1ff3b7b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 235,
          "y": 220
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      keys:
        simple: Match
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set multiple keys/values to the context.
      id: 46a155ec-16c3-40b1-8e60-78d17bcb0992
      iscommand: false
      name: Flag match
      script: SetMultipleValues
      type: regular
      version: -1
    taskid: 46a155ec-16c3-40b1-8e60-78d17bcb0992
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -120,
          "y": 410
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Match
      value:
        simple: "false"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: d3341656-7688-4ded-83ac-eb96ce17a488
      iscommand: false
      name: No Match
      script: Set
      type: regular
      version: -1
    taskid: d3341656-7688-4ded-83ac-eb96ce17a488
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 580,
          "y": 410
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: "This playbook is used to loop over every alert in a Cortex XDR
        incident. \nSupported alert categories:\n- Malware\n- Port Scan"
      id: ff4f3ed5-d089-40f4-89fb-a6dab77e980c
      iscommand: false
      name: Cortex XDR Alerts Handling
      playbookId: Cortex XDR Alerts Handling
      type: playbook
      version: -1
    taskid: ff4f3ed5-d089-40f4-89fb-a6dab77e980c
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -120,
          "y": 590
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Incident.alerts.category
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: PaloAltoNetworksXDR.Incident.alerts.alert_id
                    operator: isEqualString
                    right:
                      iscontext: true
                      value:
                        simple: inputs.alert_id
                root: PaloAltoNetworksXDR
          operator: isEqualString
          right:
            value:
              simple: Malware
      label: Malware
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Incident.alerts.name
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: PaloAltoNetworksXDR.Incident.alerts.alert_id
                    operator: isEqualString
                    right:
                      iscontext: true
                      value:
                        simple: inputs.alert_id
                root: PaloAltoNetworksXDR
          operator: isEqualString
          right:
            value:
              simple: Port Scan
      label: Port Scan
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "8"
      Malware:
      - "10"
      Port Scan:
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Choose playbook to run by alert category.
      id: 66b67919-1a92-4dea-826d-166b4464a2c7
      iscommand: false
      name: Choose playbook by category
      type: condition
      version: -1
    taskid: 66b67919-1a92-4dea-826d-166b4464a2c7
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1600,
          "y": 260
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bcc797d5-8e7e-4de8-8dd5-1f13890deb95
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: bcc797d5-8e7e-4de8-8dd5-1f13890deb95
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1600,
          "y": 610
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      incident_id:
        complex:
          root: inputs.incident_id
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cortex XDR - IR
      description: Returns additional data for the specified incident, for example,
        related alerts, file artifacts, network artifacts, and so on.
      id: 79b1b08a-4a65-4427-841c-82a8bff1b085
      iscommand: true
      name: Cortex XDR - get incident extra data
      script: Cortex XDR - IR|||xdr-get-incident-extra-data
      type: regular
      version: -1
    taskid: 79b1b08a-4a65-4427-841c-82a8bff1b085
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1600,
          "y": 85
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: cd3ccf0b-bbd4-40f3-8f39-e590d79464f7
      iscommand: false
      name: Other alert category
      type: title
      version: -1
    taskid: cd3ccf0b-bbd4-40f3-8f39-e590d79464f7
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 2040,
          "y": 435
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      BlockAttackerIP:
        simple: "False"
      OnCall:
        simple: "false"
      xdr_alert_id:
        complex:
          root: inputs.alert_id
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: "Investigates a Cortex XDR incident containing internal port scan
        alerts. The playbook:\n- Syncs data with Cortex XDR.\n- Notifies management
        about a compromised host.\n- Escalates the incident in case of lateral movement
        alert detection.\n\nThe playbook is designed to run as a sub-playbook in 'Cortex
        XDR Incident Handling - v3 & Cortex XDR Alerts Handling'. \nIt depends on
        the data from the parent playbooks and can not be used as a standalone version."
      id: 5047b7a3-82cf-4218-8ef4-650875278421
      iscommand: false
      name: Cortex XDR - Port Scan - Adjusted
      playbookId: Cortex XDR - Port Scan - Adjusted
      type: playbook
      version: -1
    taskid: 5047b7a3-82cf-4218-8ef4-650875278421
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1600,
          "y": 435
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      endpoint_id:
        complex:
          accessor: endpoint_id
          filters:
          - - left:
                iscontext: true
                value:
                  simple: PaloAltoNetworksXDR.Incident.alerts.alert_id
              operator: isEqualString
              right:
                iscontext: true
                value:
                  simple: inputs.alert_id
          root: PaloAltoNetworksXDR.Incident.alerts
      file_name:
        complex:
          accessor: action_file_name
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: PaloAltoNetworksXDR.Incident.alerts.action_file_name
              operator: in
              right:
                iscontext: true
                value:
                  simple: PaloAltoNetworksXDR.Incident.file_artifacts.file_name
          - - left:
                iscontext: true
                value:
                  simple: PaloAltoNetworksXDR.Incident.alerts.alert_id
              operator: isEqualString
              right:
                iscontext: true
                value:
                  simple: inputs.alert_id
          root: PaloAltoNetworksXDR.Incident.alerts
      file_path:
        complex:
          accessor: action_file_path
          filters:
          - - left:
                iscontext: true
                value:
                  simple: PaloAltoNetworksXDR.Incident.alerts.alert_id
              operator: isEqualString
              right:
                iscontext: true
                value:
                  simple: inputs.alert_id
          root: PaloAltoNetworksXDR.Incident.alerts
      file_sha256:
        complex:
          accessor: action_file_sha256
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: PaloAltoNetworksXDR.Incident.alerts.action_file_sha256
              operator: in
              right:
                iscontext: true
                value:
                  simple: PaloAltoNetworksXDR.Incident.file_artifacts.file_sha256
          - - left:
                iscontext: true
                value:
                  simple: PaloAltoNetworksXDR.Incident.alerts.alert_id
              operator: isEqualString
              right:
                iscontext: true
                value:
                  simple: inputs.alert_id
          root: PaloAltoNetworksXDR.Incident.alerts
      host_ip:
        complex:
          accessor: host_ip_list
          filters:
          - - left:
                iscontext: true
                value:
                  simple: PaloAltoNetworksXDR.Incident.alerts.alert_id
              operator: isEqualString
              right:
                iscontext: true
                value:
                  simple: inputs.alert_id
          root: PaloAltoNetworksXDR.Incident.alerts
      xdr_alert_id:
        complex:
          root: inputs.alert_id
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Investigates a Cortex XDR incident containing internal malware alerts. The playbook:
        - Enriches the infected endpoint details.
        - Lets the analyst manually retrieve the malicious file.
        - Performs file detonation.

        The playbook is used as a sub- playbook in ‘Cortex XDR Incident Handling - v2’
      id: a3338bba-8771-4740-8ece-ea200e39595e
      iscommand: false
      name: Cortex XDR - Malware Investigation
      playbookId: Cortex XDR - Malware Investigation
      type: playbook
      version: -1
    taskid: a3338bba-8771-4740-8ece-ea200e39595e
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1160,
          "y": 435
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 620,
        "width": 2540,
        "x": -120,
        "y": 65
      }
    }
  }
