contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    itemVersion: 4.8.18
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: |-
  This playbook is triggered by fetching a Palo Alto Networks Cortex XDR incident.
  The playbook syncs and updates new XDR alerts that construct the incident and triggers a sub-playbook to handle each alert by type.
  Then, the playbook performs enrichment on the incident’s indicators and hunts for related IOCs.
  Based on the severity, it lets the analyst decide whether to continue to the remediation stage or close the investigation as a false positive.
  After the remediation, if there are no new alerts, the playbook stops the alert sync and closes the XDR incident and investigation. For performing the bidirectional sync, the playbook uses the incoming and outgoing mirroring feature added in XSOAR version 6.0.0. After the Calculate Severity - Generic v2 sub-playbook’s run, Cortex XSOAR will be treated as the single source of truth for the severity field, and it will sync only from Cortex XSOAR to XDR, so manual changes for the severity field in XDR will not update in the XSOAR incident.
id: 1ac8a067-8edf-47c2-8021-ddfde8011533
inputs: []
name: 'SOCaaS - Cortex XDR incident handling '
outputs: []
sourceplaybookid: Cortex XDR incident handling v3
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2731e6f1-0a05-4cbc-84f7-4d0be1f8580d
      iscommand: false
      name: ""
      version: -1
    taskid: 2731e6f1-0a05-4cbc-84f7-4d0be1f8580d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 582.5,
          "y": 50
        }
      }
  "2":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: PaloAltoNetworksXDR.Incident.severity
          operator: inList
          right:
            value:
              simple: medium,high,critical
      label: "yes"
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    note: false
    quietmode: 2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ad7398e2-f2a3-484a-8e6f-ee63b914670d
      iscommand: false
      name: Should handle the incident?
      type: condition
      version: -1
    taskid: ad7398e2-f2a3-484a-8e6f-ee63b914670d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 582.5,
          "y": 370
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
      - "12"
      - "15"
    note: false
    quietmode: 2
    scriptarguments:
      alert_id:
        simple: ${PaloAltoNetworksXDR.Incident.incident_id}
      created_at:
        complex:
          accessor: creation_time
          root: PaloAltoNetworksXDR.Incident
          transformers:
          - operator: TimeStampToDate
      customer_id:
        simple: "33096"
      modified_at:
        complex:
          accessor: modification_time
          root: PaloAltoNetworksXDR.Incident
          transformers:
          - operator: TimeStampToDate
      name:
        simple: ${incident.name}
      provider_id:
        simple: ${incident.sourceInstance}
      raw_data:
        complex:
          root: incident
          transformers:
          - operator: Stringify
      severity:
        complex:
          accessor: severity
          root: incident
          transformers:
          - args:
              input_values:
                value:
                  simple: 0,1,2,3,4,5
              mapped_values:
                value:
                  simple: LOW,LOW,MEDIUM,MEDIUM,HIGH,HIGH
            operator: MapValuesTransformer
    separatecontext: false
    skipunavailable: false
    task:
      brand: MSS Portal - MDR
      description: Create an alert using Portal's MDR API
      id: 2b13e64c-860a-4279-80e4-83191f1988ab
      iscommand: true
      name: Create a case in portal
      script: MSS Portal - MDR|||mssportal-create-alert
      type: regular
      version: -1
    taskid: 2b13e64c-860a-4279-80e4-83191f1988ab
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: eb0a7bf1-a9b3-4622-81f0-335abd7ecdd9
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: eb0a7bf1-a9b3-4622-81f0-335abd7ecdd9
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 695,
          "y": 2470
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 2
    scriptarguments:
      case_id:
        simple: ${MSSPortal.Alert.id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: MSS Portal - MDR
      description: Acknowledge case to change the status to "IN_PROGRESS".
      id: 98e88d96-27c5-4d2f-8bb9-935d71c60d70
      iscommand: true
      name: Update the case in portal to change the case status from pending to inprogress
      script: MSS Portal - MDR|||mssportal-acknowledge-case
      type: regular
      version: -1
    taskid: 98e88d96-27c5-4d2f-8bb9-935d71c60d70
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1420
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      case_id:
        simple: ${MSSPortal.Alert.id}
      status:
        simple: CLOSED
    separatecontext: false
    skipunavailable: false
    task:
      brand: MSS Portal - MDR
      description: Update a case.
      id: 35da58ca-f335-4d90-88b5-70d4c81917ff
      iscommand: true
      name: Close incident
      script: MSS Portal - MDR|||mssportal-update-case
      type: regular
      version: -1
    taskid: 35da58ca-f335-4d90-88b5-70d4c81917ff
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 2295
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      Digits:
        simple: "False"
      Length:
        simple: "1"
      Lowercase:
        simple: "True"
      Punctuation:
        simple: "False"
      Uppercase:
        simple: "False"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Generates random string
      id: 894b8a8f-58d1-4a7c-8035-7acab5cfebd1
      iscommand: false
      name: Check if the endpoint is VIP or server
      script: GenerateRandomString
      type: regular
      version: -1
    taskid: 894b8a8f-58d1-4a7c-8035-7acab5cfebd1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1770
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: PaloAltoNetworksXDR.Incident.alert_categories
          operator: containsGeneral
          right:
            value:
              simple: Malware
      label: "yes"
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "yes":
      - "23"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ""
      iscommand: false
      name: Malware on Host
      type: condition
      version: -1
    taskid: b7114c26-ba33-4956-871e-9a65282e4f36
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 43c6b140-9c2d-421d-8b47-6dc0eb975fa8
      iscommand: false
      name: 'Alert Category #1'
      type: title
      version: -1
    taskid: 43c6b140-9c2d-421d-8b47-6dc0eb975fa8
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 2310
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      Digits:
        simple: "False"
      Length:
        simple: "1"
      Lowercase:
        simple: "True"
      Punctuation:
        simple: "False"
      Uppercase:
        simple: "False"
      ignore-outputs:
        simple: "false"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Generates random string
      id: ef731c5a-1890-4069-8fb4-8891fd604dbd
      iscommand: false
      name: Check if false positive
      script: GenerateRandomString
      type: regular
      version: -1
    taskid: ef731c5a-1890-4069-8fb4-8891fd604dbd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
  "14":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: RandomString
          operator: match
          right:
            value:
              simple: '[a-f]'
      label: "yes"
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fc813a6a-639e-42a6-8a51-d85819b3ee19
      iscommand: false
      name: Is false positive?
      type: condition
      version: -1
    taskid: fc813a6a-639e-42a6-8a51-d85819b3ee19
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7377f5a5-5915-4b53-83fd-28df64671054
      iscommand: false
      name: 'Alert Category #2'
      type: title
      version: -1
    taskid: 7377f5a5-5915-4b53-83fd-28df64671054
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 2310
        }
      }
  "16":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: RandomString
          operator: inList
          right:
            value:
              simple: '[a-o]'
      label: "yes"
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "18"
      "yes":
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0aefbb0d-ff55-4751-89af-9a578924a28d
      iscommand: false
      name: Is the endpoint VIP or Server?
      type: condition
      version: -1
    taskid: 0aefbb0d-ff55-4751-89af-9a578924a28d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1945
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b7059362-3571-477d-8292-dd655a35f21d
      iscommand: false
      name: Create portal task
      type: regular
      version: -1
    taskid: b7059362-3571-477d-8292-dd655a35f21d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2295
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cortex XDR - IR
      description: Isolates the specified endpoint.
      id: fcc8756a-7107-4c8d-8bd2-5bf0dc0e2d39
      iscommand: true
      name: handle endpoint isolation
      script: Cortex XDR - IR|||xdr-endpoint-isolate
      type: regular
      version: -1
    taskid: fcc8756a-7107-4c8d-8bd2-5bf0dc0e2d39
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f420bda0-89ba-492c-809c-ef98c4c5a91e
      iscommand: false
      name: create task for customer to clean up host
      type: regular
      version: -1
    taskid: f420bda0-89ba-492c-809c-ef98c4c5a91e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
  "21":
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b1e9b94a-c11b-4557-8f7f-acc252a682c8
      iscommand: false
      name: create a task to assign it to customer
      type: regular
      version: -1
    taskid: b1e9b94a-c11b-4557-8f7f-acc252a682c8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1595
        }
      }
  "22":
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      incident_id:
        simple: ${incident.xdrincidentid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cortex XDR - IR
      description: Returns additional data for the specified incident, for example,
        related alerts, file artifacts, network artifacts, and so on.
      id: f23da29a-008e-4ebc-8e07-0836d318de6a
      iscommand: true
      name: 'Get extra incident data '
      script: Cortex XDR - IR|||xdr-get-incident-extra-data
      type: regular
      version: -1
    taskid: f23da29a-008e-4ebc-8e07-0836d318de6a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 582.5,
          "y": 195
        }
      }
  "23":
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      IncidentID:
        simple: ${PaloAltoNetworksXDR.Incident.incident_id}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 197c5278-c15c-4eb0-8b03-876dc1c8c4bf
      iscommand: false
      name: SOCaaS - Cortex XDR Malware - Incident Enrichment
      playbookId: a3154fd7-21d8-4067-8c32-cd7bcd4afe07
      type: playbook
      version: -1
    taskid: 197c5278-c15c-4eb0-8b03-876dc1c8c4bf
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 480,
          "y": 885
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2485,
        "width": 2100,
        "x": 50,
        "y": 50
      }
    }
  }
