contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    itemVersion: 4.8.18
    packID: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: |-
  This playbook is triggered by fetching a Palo Alto Networks Cortex XDR incident.
  The playbook syncs and updates new XDR alerts that construct the incident and triggers a sub-playbook to handle each alert by type.
  Then, the playbook performs enrichment on the incident’s indicators and hunts for related IOCs.
  Based on the severity, it lets the analyst decide whether to continue to the remediation stage or close the investigation as a false positive.
  After the remediation, if there are no new alerts, the playbook stops the alert sync and closes the XDR incident and investigation. For performing the bidirectional sync, the playbook uses the incoming and outgoing mirroring feature added in XSOAR version 6.0.0. After the Calculate Severity - Generic v2 sub-playbook’s run, Cortex XSOAR will be treated as the single source of truth for the severity field, and it will sync only from Cortex XSOAR to XDR, so manual changes for the severity field in XDR will not update in the XSOAR incident.
id: 1ac8a067-8edf-47c2-8021-ddfde8011533
inputs: []
name: SOCaaS - Cortex XDR incident handling
outputs: []
sourceplaybookid: Cortex XDR incident handling v3
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2dd4904d-513e-4071-8b3e-25aeba751b52
      iscommand: false
      name: ""
      version: -1
    taskid: 2dd4904d-513e-4071-8b3e-25aeba751b52
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 1700,
          "y": -2450
        }
      }
  "2":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: PaloAltoNetworksXDR.Incident.severity
          operator: inList
          right:
            value:
              simple: medium,high,critical
      label: "yes"
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    note: false
    quietmode: 2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: cab3c7e6-e7b0-4401-86e7-a76a6805a2f3
      iscommand: false
      name: Should handle the incident?
      type: condition
      version: -1
    taskid: cab3c7e6-e7b0-4401-86e7-a76a6805a2f3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1700,
          "y": -2030
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
      - "12"
      - "15"
    note: false
    quietmode: 2
    scriptarguments:
      alert_id:
        simple: ${PaloAltoNetworksXDR.Incident.incident_id}
      created_at:
        complex:
          accessor: creation_time
          root: PaloAltoNetworksXDR.Incident
          transformers:
          - operator: TimeStampToDate
      customer_id:
        simple: "33096"
      modified_at:
        complex:
          accessor: modification_time
          root: PaloAltoNetworksXDR.Incident
          transformers:
          - operator: TimeStampToDate
      name:
        simple: ${incident.name}
      provider_id:
        simple: ${incident.sourceInstance}
      raw_data:
        complex:
          root: incident
          transformers:
          - operator: Stringify
      severity:
        complex:
          accessor: severity
          root: incident
          transformers:
          - args:
              input_values:
                value:
                  simple: 0,1,2,3,4,5
              mapped_values:
                value:
                  simple: LOW,LOW,MEDIUM,MEDIUM,HIGH,HIGH
            operator: MapValuesTransformer
    separatecontext: false
    skipunavailable: false
    task:
      brand: MSS Portal - MDR
      description: Create an alert using Portal's MDR API
      id: 53b829f1-57cf-43e0-86d6-e098601a0f2d
      iscommand: true
      name: Create a case in portal
      script: MSS Portal - MDR|||mssportal-create-alert
      type: regular
      version: -1
    taskid: 53b829f1-57cf-43e0-86d6-e098601a0f2d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1190,
          "y": -1760
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4315f52d-ad89-488f-8e38-276cffab0091
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 4315f52d-ad89-488f-8e38-276cffab0091
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1240,
          "y": 360
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 2
    scriptarguments:
      case_id:
        simple: ${MSSPortal.Alert.id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: MSS Portal - MDR
      description: Acknowledge case to change the status to "IN_PROGRESS".
      id: 0e3c54c3-e581-4d7b-8461-f950db9d838d
      iscommand: true
      name: Update the case in portal to change the case status from pending to inprogress
      script: MSS Portal - MDR|||mssportal-acknowledge-case
      type: regular
      version: -1
    taskid: 0e3c54c3-e581-4d7b-8461-f950db9d838d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 600,
          "y": -580
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      case_id:
        simple: ${MSSPortal.Alert.id}
      status:
        simple: CLOSED
    separatecontext: false
    skipunavailable: false
    task:
      brand: MSS Portal - MDR
      description: Update a case.
      id: 2b86c119-9638-4e45-84da-80d477719ca3
      iscommand: true
      name: Close incident
      script: MSS Portal - MDR|||mssportal-update-case
      type: regular
      version: -1
    taskid: 2b86c119-9638-4e45-84da-80d477719ca3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 130,
          "y": -580
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      Digits:
        simple: "False"
      Length:
        simple: "1"
      Lowercase:
        simple: "True"
      Punctuation:
        simple: "False"
      Uppercase:
        simple: "False"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Generates random string
      id: 811eaec1-4190-4356-83e6-99655d9e1507
      iscommand: false
      name: Check if the endpoint is VIP or server
      script: GenerateRandomString
      type: regular
      version: -1
    taskid: 811eaec1-4190-4356-83e6-99655d9e1507
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 600,
          "y": -315
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: PaloAltoNetworksXDR.Incident.alert_categories
          operator: containsGeneral
          right:
            value:
              simple: Malware
      label: "yes"
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "yes":
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5350567d-b49a-4402-8667-c6d4db659702
      iscommand: false
      name: Malware on Host
      type: condition
      version: -1
    taskid: 5350567d-b49a-4402-8667-c6d4db659702
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 400,
          "y": -1330
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 53bf3e45-4849-4e9f-80f3-bd2e53c1b19c
      iscommand: false
      name: 'Alert Category #1'
      type: title
      version: -1
    taskid: 53bf3e45-4849-4e9f-80f3-bd2e53c1b19c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1040,
          "y": -1320
        }
      }
  "13":
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      Digits:
        simple: "False"
      Length:
        simple: "1"
      Lowercase:
        simple: "True"
      Punctuation:
        simple: "False"
      Uppercase:
        simple: "False"
      ignore-outputs:
        simple: "false"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Generates random string
      id: c70a9a55-4b42-4670-8054-fb9dcba38035
      iscommand: false
      name: Check if false positive
      script: GenerateRandomString
      type: regular
      version: -1
    taskid: c70a9a55-4b42-4670-8054-fb9dcba38035
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 400,
          "y": -945
        }
      }
  "14":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: RandomString
          operator: match
          right:
            value:
              simple: '[a-f]'
      label: "yes"
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: dd52d7b8-8170-4555-8d6d-9178bacc223f
      iscommand: false
      name: Is false positive?
      type: condition
      version: -1
    taskid: dd52d7b8-8170-4555-8d6d-9178bacc223f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 400,
          "y": -780
        }
      }
  "15":
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e0ac8dd9-7a69-4e7e-87ee-d333b02b07dd
      iscommand: false
      name: 'Alert Category #2'
      type: title
      version: -1
    taskid: e0ac8dd9-7a69-4e7e-87ee-d333b02b07dd
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1670,
          "y": -1330
        }
      }
  "16":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: RandomString
          operator: inList
          right:
            value:
              simple: '[a-o]'
      label: "yes"
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "18"
      "yes":
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 228c1c45-1720-4a1f-83d5-c37c479c73e1
      iscommand: false
      name: Is the endpoint VIP or Server?
      type: condition
      version: -1
    taskid: 228c1c45-1720-4a1f-83d5-c37c479c73e1
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 600,
          "y": -170
        }
      }
  "17":
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b78e3e34-2435-4fda-8496-0470e367eca1
      iscommand: false
      name: Create portal task
      type: regular
      version: -1
    taskid: b78e3e34-2435-4fda-8496-0470e367eca1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 400,
          "y": 5
        }
      }
  "18":
    continueonerror: true
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cortex XDR - IR
      description: Isolates the specified endpoint.
      id: 54d7bb22-f781-4ac6-82a8-ae55881e6d56
      iscommand: true
      name: handle endpoint isolation
      script: Cortex XDR - IR|||xdr-endpoint-isolate
      type: regular
      version: -1
    taskid: 54d7bb22-f781-4ac6-82a8-ae55881e6d56
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 820,
          "y": 5
        }
      }
  "19":
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 674b116c-9c96-49eb-8e5e-18b162114f66
      iscommand: false
      name: create task for customer to clean up host
      type: regular
      version: -1
    taskid: 674b116c-9c96-49eb-8e5e-18b162114f66
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 820,
          "y": 160
        }
      }
  "21":
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f49a883b-1c24-428f-84d3-782a4d81ed74
      iscommand: false
      name: create a task to assign it to customer
      type: regular
      version: -1
    taskid: f49a883b-1c24-428f-84d3-782a4d81ed74
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 600,
          "y": -455
        }
      }
  "22":
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      incident_id:
        simple: ${incident.xdrincidentid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cortex XDR - IR
      description: Returns additional data for the specified incident, for example,
        related alerts, file artifacts, network artifacts, and so on.
      id: 581ab911-e819-4964-8e8e-181f33e7cd11
      iscommand: true
      name: 'Get extra incident data '
      script: Cortex XDR - IR|||xdr-get-incident-extra-data
      type: regular
      version: -1
    taskid: 581ab911-e819-4964-8e8e-181f33e7cd11
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1700,
          "y": -2270
        }
      }
  "24":
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      IncidentID:
        simple: ${PaloAltoNetworksXDR.Incident.incident_id}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        This playbook is part of the 'Malware Investigation And Response' pack. For more information, refer to https://xsoar.pan.dev/docs/reference/packs/malware-investigation-and-response.
        This playbook enriches the Cortex XDR incident. The enrichment is done on the involved endpoint and Mitre technique ID information, and sets the 'Malware-Investigation and Response' layout.
      id: 5df725ad-a0e0-4196-875e-04d326a355c6
      iscommand: false
      name: Cortex XDR Malware - Incident Enrichment
      playbookId: Cortex XDR Malware - Incident Enrichment
      type: playbook
      version: -1
    taskid: 5df725ad-a0e0-4196-875e-04d326a355c6
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 400,
          "y": -1140
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2875,
        "width": 1950,
        "x": 130,
        "y": -2450
      }
    }
  }
