contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: d702f63a-a525-4139-8031-9f79abb651df
inputs:
- description: 'Alerts within the incident '
  key: 'alerts '
  playbookInputQuery: null
  required: true
  value:
    simple: alert
- description: Default value is yes. False means to stop execution
  key: 'Continue with execution '
  playbookInputQuery: null
  required: true
  value:
    simple: "yes"
name: Benign Security Testing
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ea7962db-48e7-42d1-8c29-fa6d70a7223d
      iscommand: false
      name: ""
      version: -1
    taskid: ea7962db-48e7-42d1-8c29-fa6d70a7223d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.alerts.source
          operator: hasLength
          right:
            value:
              simple: XDR Agent
      - - left:
            iscontext: true
            value:
              simple: inputs.alerts.host_ip
          operator: in
          right:
            value:
              simple: list.authorizedhost
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b366d235-afe6-4c3e-837f-5e4aa9abf66b
      iscommand: false
      name: 'Scenario Match? '
      type: condition
      version: -1
    taskid: b366d235-afe6-4c3e-837f-5e4aa9abf66b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -30,
          "y": 360
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: 'inputs.Continue with execution '
          operator: isEqualString
          right:
            value:
              simple: "yes"
      label: "yes"
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b105e28a-fb1a-4300-8161-054e1d5e56dd
      iscommand: false
      name: Prompt User
      type: condition
      version: -1
    taskid: b105e28a-fb1a-4300-8161-054e1d5e56dd
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 190
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 182b9f40-674b-4d30-87b9-be4caa3b0492
      iscommand: false
      name: Exit
      type: regular
      version: -1
    taskid: 182b9f40-674b-4d30-87b9-be4caa3b0492
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 610,
          "y": 360
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Match
      value:
        simple: "true"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: b1b818ca-59c1-4f96-86f8-4e2fc3fbc237
      iscommand: false
      name: 'Flag as Match '
      script: Set
      type: regular
      version: -1
    taskid: b1b818ca-59c1-4f96-86f8-4e2fc3fbc237
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -280,
          "y": 570
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Match
      value:
        simple: "False"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 6f4aec6f-4967-4eff-8fd0-c40bed3e3c02
      iscommand: false
      name: 'Flag Unmatched '
      script: Set
      type: regular
      version: -1
    taskid: 6f4aec6f-4967-4eff-8fd0-c40bed3e3c02
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 180,
          "y": 560
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 615,
        "width": 1270,
        "x": -280,
        "y": 50
      }
    }
  }
