contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: d702f63a-a525-4139-8031-9f79abb651df
inputs:
- description: 'each alert in cortex xdr case '
  key: alert
  playbookInputQuery: null
  required: true
  value:
    complex:
      accessor: alerts
      root: PaloAltoNetworksXDR.Incident.[0]
name: Scenario
outputs:
- contextPath: Match
  description: match
  type: unknown
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ea7962db-48e7-42d1-8c29-fa6d70a7223d
      iscommand: false
      name: ""
      version: -1
    taskid: ea7962db-48e7-42d1-8c29-fa6d70a7223d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.alert.source
          operator: isEqualString
          right:
            value:
              simple: XDR Agent
      - - left:
            iscontext: true
            value:
              simple: inputs.alerts.host_ip
          operator: in
          right:
            value:
              simple: list.authorizedhost
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7a72f385-0e5c-4fd9-8568-61c8b1ff3b7b
      iscommand: false
      name: 'Scenario Match? '
      type: condition
      version: -1
    taskid: 7a72f385-0e5c-4fd9-8568-61c8b1ff3b7b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 210
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Match
      value:
        simple: "true"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: a28e4d14-679e-432f-8cea-94e268dd86a6
      iscommand: false
      name: Flag match
      script: Set
      type: regular
      version: -1
    taskid: a28e4d14-679e-432f-8cea-94e268dd86a6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -90,
          "y": 400
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Match
      value:
        simple: "false"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: d3341656-7688-4ded-83ac-eb96ce17a488
      iscommand: false
      name: No Match
      script: Set
      type: regular
      version: -1
    taskid: d3341656-7688-4ded-83ac-eb96ce17a488
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 610,
          "y": 400
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 445,
        "width": 1080,
        "x": -90,
        "y": 50
      }
    }
  }
