contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: d702f63a-a525-4139-8031-9f79abb651df
inputs: []
name: Benign Security Testing
outputs:
- contextPath: Match
  description: match
  type: boolean
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ea7962db-48e7-42d1-8c29-fa6d70a7223d
      iscommand: false
      name: ""
      version: -1
    taskid: ea7962db-48e7-42d1-8c29-fa6d70a7223d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.alerts.source
          operator: hasLength
          right:
            value:
              simple: XDR Agent
      - - left:
            iscontext: true
            value:
              simple: inputs.alerts.host_ip
          operator: in
          right:
            value:
              simple: list.authorizedhost
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b366d235-afe6-4c3e-837f-5e4aa9abf66b
      iscommand: false
      name: 'Scenario Match? '
      type: condition
      version: -1
    taskid: b366d235-afe6-4c3e-837f-5e4aa9abf66b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 210
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Match
      value:
        simple: "true"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: b1b818ca-59c1-4f96-86f8-4e2fc3fbc237
      iscommand: false
      name: 'Flag as Match '
      script: Set
      type: regular
      version: -1
    taskid: b1b818ca-59c1-4f96-86f8-4e2fc3fbc237
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 10,
          "y": 430
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Match
      value:
        simple: "false"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 4629b8e4-7b7a-4be2-8c21-c576b0d06ba5
      iscommand: false
      name: 'Flag Unmatched '
      script: Set
      type: regular
      version: -1
    taskid: 4629b8e4-7b7a-4be2-8c21-c576b0d06ba5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 540,
          "y": 420
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 475,
        "width": 910,
        "x": 10,
        "y": 50
      }
    }
  }
