contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    itemVersion: 4.8.18
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: |-
  This playbook is triggered by fetching a Palo Alto Networks Cortex XDR incident.
  The playbook syncs and updates new XDR alerts that construct the incident and triggers a sub-playbook to handle each alert by type.
  Then, the playbook performs enrichment on the incident’s indicators and hunts for related IOCs.
  Based on the severity, it lets the analyst decide whether to continue to the remediation stage or close the investigation as a false positive.
  After the remediation, if there are no new alerts, the playbook stops the alert sync and closes the XDR incident and investigation. For performing the bidirectional sync, the playbook uses the incoming and outgoing mirroring feature added in XSOAR version 6.0.0. After the Calculate Severity - Generic v2 sub-playbook’s run, Cortex XSOAR will be treated as the single source of truth for the severity field, and it will sync only from Cortex XSOAR to XDR, so manual changes for the severity field in XDR will not update in the XSOAR incident.
id: f2c50835-34e9-4929-8934-57209a3c778c
inputs: []
name: SOCaaS - Cortex XDR incident handling_copy
outputs: []
sourceplaybookid: Cortex XDR incident handling v3
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "26"
    note: false
    quietmode: 2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c71462ee-dfd7-4563-8ef2-843d955b631e
      iscommand: false
      name: ""
      version: -1
    taskid: c71462ee-dfd7-4563-8ef2-843d955b631e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 910,
          "y": 65
        }
      }
  "22":
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "34"
    note: false
    quietmode: 2
    scriptarguments:
      incident_id:
        simple: ${incident.xdrincidentid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cortex XDR - IR
      description: Returns additional data for the specified incident, for example,
        related alerts, file artifacts, network artifacts, and so on.
      id: 3999e9ae-d395-42e5-83ae-65fe2b52ea8f
      iscommand: true
      name: 'Get extra incident data '
      script: Cortex XDR - IR|||xdr-get-incident-extra-data
      type: regular
      version: -1
    taskid: 3999e9ae-d395-42e5-83ae-65fe2b52ea8f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 750
        }
      }
  "26":
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "42"
    note: false
    quietmode: 2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 10d2c4e7-4d41-475a-8a8b-36724387683d
      iscommand: false
      name: Get customer id
      script: a4743b1e-d208-4ff0-8272-d272c558ca46
      type: regular
      version: -1
    taskid: 10d2c4e7-4d41-475a-8a8b-36724387683d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 225
        }
      }
  "34":
    continueonerrortype: ""
    id: "34"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "35"
      - "47"
    note: false
    quietmode: 0
    scriptarguments:
      alerts:
        complex:
          accessor: alert_id
          root: PaloAltoNetworksXDR.Incident.alerts
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 63bc59c1-c4fc-4087-8878-023e6d585cef
      iscommand: false
      name: Scenario
      playbookId: d702f63a-a525-4139-8031-9f79abb651df
      type: playbook
      version: -1
    taskid: 63bc59c1-c4fc-4087-8878-023e6d585cef
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 910,
          "y": 925
        }
      }
  "35":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: None
          operator: isNotEmpty
          right:
            value: {}
        - left:
            iscontext: true
            value:
              simple: (NGFW)IPS
          operator: isNotEmpty
      label: 'Mixed Batch of Potential and Benign '
    - condition:
      - - left:
            iscontext: true
            value:
              simple: BenignSecuirty
          operator: isEmpty
        - left:
            iscontext: true
            value:
              simple: (NGFW)IPS
          operator: isEmpty
      label: Only Potential Scenario
    - condition:
      - - left:
            iscontext: true
            value:
              simple: BenignSecuirty
          operator: isEmpty
        - left:
            iscontext: true
            value:
              simple: None
          operator: isEmpty
      label: Only Benign
    - condition:
      - - left:
            iscontext: true
            value:
              simple: None
          operator: isEmpty
      label: "Null"
    continueonerrortype: ""
    id: "35"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      'Mixed Batch of Potential and Benign ':
      - "38"
      "Null":
      - "48"
      Only Benign:
      - "46"
      Only Potential Scenario:
      - "45"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 37a9363e-4469-494e-863e-5e63285b4a82
      iscommand: false
      name: Different Scenarios?
      type: condition
      version: -1
    taskid: 37a9363e-4469-494e-863e-5e63285b4a82
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 582.5,
          "y": 1100
        }
      }
  "38":
    continueonerrortype: ""
    id: "38"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "39"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 960de740-1efc-40f2-85ce-5b2bf03ea3b6
      iscommand: false
      name: Mixed Scenarios
      type: title
      version: -1
    taskid: 960de740-1efc-40f2-85ce-5b2bf03ea3b6
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1275
        }
      }
  "39":
    continueonerrortype: ""
    id: "39"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "50"
    note: false
    quietmode: 0
    scriptarguments:
      incident_id:
        simple: ${PaloAltoNetworksXDR.Incident.incident_id}
      status:
        simple: UNDER_INVESTIGATION
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cortex XDR - IR
      description: Updates one or more fields of a specified incident. Missing fields
        will be ignored. To remove the assignment for an incident, pass a null value
        in the assignee email argument.
      id: 1d9e530f-4691-48af-8e27-42eb2e04cdf6
      iscommand: true
      name: Under Investigation
      script: Cortex XDR - IR|||xdr-update-incident
      type: regular
      version: -1
    taskid: 1d9e530f-4691-48af-8e27-42eb2e04cdf6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1430
        }
      }
  "42":
    continueonerrortype: ""
    id: "42"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "43"
    note: false
    quietmode: 2
    scriptarguments:
      caseSource:
        simple: Cortex XDR
      caseTitle:
        simple: ${PaloAltoNetworksXDR.Incident.description}  - ${PaloAltoNetworksXDR.Incident.incident_id}
      casecreation_casesource:
        simple: XSOAR_CORTEX_XDR
      casecreation_casetitle:
        simple: ${PaloAltoNetworksXDR.Incident.description}  - ${PaloAltoNetworksXDR.Incident.incident_id}
      casecreation_customerid:
        simple: ${MSSPortal.CustomerInfo.id}
      casecreation_description:
        simple: ${PaloAltoNetworksXDR.Incident.description}
      casecreation_priority:
        simple: ${PaloAltoNetworksXDR.Incident.severity}
      casecreation_servicecomponent:
        simple: SOC
      customerId:
        simple: ${MSSPortal.tsp_customer_id}
      description:
        simple: ${PaloAltoNetworksXDR.Incident.description}
      priority:
        simple: ${PaloAltoNetworksXDR.Incident.severity}
      serviceComponent:
        simple: SOC
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'mssportal-create-case command: Returns a MSSPortal case'
      id: 5af75085-409f-4f4d-8572-b1a8b784f65b
      iscommand: true
      name: Create a case in portal
      script: '|||mssportal-create-case'
      type: regular
      version: -1
    taskid: 5af75085-409f-4f4d-8572-b1a8b784f65b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 400
        }
      }
  "43":
    continueonerrortype: ""
    id: "43"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 2
    scriptarguments:
      alertcreation_customerid:
        simple: ${MSSPortal.CaseInfo.customerId}
      alertcreation_name:
        simple: ${MSSPortal.CaseInfo.caseTitle}
      alertcreation_severity:
        simple: ${MSSPortal.CaseInfo.priority}
      alertcreation_sourcealertid:
        simple: ${PaloAltoNetworksXDR.Incident.incident_id}
      alertcreation_sourcecreatedat:
        complex:
          accessor: creation_time
          root: PaloAltoNetworksXDR.Incident
          transformers:
          - operator: TimeStampToDate
      alertcreation_sourceid:
        simple: ${MSSPortal.CaseInfo.caseSource}
      alertcreation_sourcemodifiedat:
        complex:
          accessor: modification_time
          root: PaloAltoNetworksXDR.Incident
          transformers:
          - operator: TimeStampToDate
      caseDescription:
        simple: ${MSSPortal.Case.description}
      caseTitle:
        simple: ${MSSPortal.Case.caseTitle}
      customerId:
        simple: ${MSSPortal.Case.customerId}
      investigationCaseId:
        simple: ${MSSPortal.Case.id}
      name:
        simple: ${MSSPortal.Case.caseTitle}
      severity:
        simple: ${MSSPortal.Case.priority}
      sourceAlertId:
        simple: ${PaloAltoNetworksXDR.Incident.incident_id}
      sourceCreatedAt:
        complex:
          accessor: creation_time
          root: PaloAltoNetworksXDR.Incident
          transformers:
          - operator: TimeStampToDate
      sourceId:
        simple: ${MSSPortal.Case.caseSource}
      sourceModifiedAt:
        complex:
          accessor: modification_time
          root: PaloAltoNetworksXDR.Incident
          transformers:
          - operator: TimeStampToDate
      sourceRaw:
        simple: ${PaloAltoNetworksXDR.Incident}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'mssportal-create-alert command: Returns a MSSPortal alert'
      id: db9cd46f-cc50-4d2f-8aea-377775911a00
      iscommand: true
      name: Create an alert to the case
      script: '|||mssportal-create-alert'
      type: regular
      version: -1
    taskid: db9cd46f-cc50-4d2f-8aea-377775911a00
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 575
        }
      }
  "45":
    continueonerrortype: ""
    id: "45"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "49"
    note: false
    quietmode: 0
    scriptarguments:
      incident_id:
        simple: ${PaloAltoNetworksXDR.Incident.incident_id}
      resolve_comment:
        simple: 'All potential scenarios. Still working progress '
      status:
        simple: UNDER_INVESTIGATION
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cortex XDR - IR
      description: Updates one or more fields of a specified incident. Missing fields
        will be ignored. To remove the assignment for an incident, pass a null value
        in the assignee email argument.
      id: b42f5183-fb8d-4723-8e98-2c1ff73fc509
      iscommand: true
      name: Potential Incident
      script: Cortex XDR - IR|||xdr-update-incident
      type: regular
      version: -1
    taskid: b42f5183-fb8d-4723-8e98-2c1ff73fc509
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 850,
          "y": 1275
        }
      }
  "46":
    continueonerrortype: ""
    id: "46"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      incident_id:
        simple: ${PaloAltoNetworksXDR.Incident.incident_id}
      resolve_comment:
        simple: Case closed as it relates only to threat activity from the Internet
          targeting external service(s). Any service facing the Internet will continuously
          face scanning and opportunistic exploitation attempts, which are not cause
          for any specific concern
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Updates one or more fields of a specified incident. Missing fields
        will be ignored. To remove the assignment for an incident, pass a null value
        in the assignee email argument.
      id: 553050e5-5e43-4071-81c8-6ee04bc34d4d
      iscommand: true
      name: Benign Close
      script: '|||xdr-update-incident'
      type: regular
      version: -1
    taskid: 553050e5-5e43-4071-81c8-6ee04bc34d4d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 350,
          "y": 1275
        }
      }
  "47":
    continueonerrortype: ""
    id: "47"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      list_stats:
        simple: None
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e6904f46-23d2-4c7b-803e-b16c32c22fdd
      iscommand: false
      name: Overview of Scenarios
      script: 1950eeb2-e086-4f71-8339-512d30419012
      type: regular
      version: -1
    taskid: e6904f46-23d2-4c7b-803e-b16c32c22fdd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1100
        }
      }
  "48":
    continueonerrortype: ""
    id: "48"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 72bd7884-6ae8-4478-8d30-911b246cb394
      iscommand: false
      name: None Match
      type: regular
      version: -1
    taskid: 72bd7884-6ae8-4478-8d30-911b246cb394
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -157.5,
          "y": 1275
        }
      }
  "49":
    continueonerrortype: ""
    id: "49"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: b4b57c22-c133-4bc6-842c-29d5a82db61f
      iscommand: false
      name: Choose the Playbook to Resolve Incident
      type: condition
      version: -1
    taskid: b4b57c22-c133-4bc6-842c-29d5a82db61f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 850,
          "y": 1460
        }
      }
  "50":
    continueonerrortype: ""
    id: "50"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f2a93d46-f217-40c2-8553-016c396d3514
      iscommand: false
      name: 'Resolve the conflict '
      type: regular
      version: -1
    taskid: f2a93d46-f217-40c2-8553-016c396d3514
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1625
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1655,
        "width": 1877.5,
        "x": -157.5,
        "y": 65
      }
    }
  }
