contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: d702f63a-a525-4139-8031-9f79abb651df
inputs:
- description: 'each alert in cortex xdr case '
  key: alert
  playbookInputQuery: null
  required: true
  value:
    complex:
      accessor: alerts
      root: PaloAltoNetworksXDR.Incident
name: Scenario
outputs:
- contextPath: SummaryAlerts.None
  description: mapping of scenario to alerts
  type: unknown
- contextPath: SummaryAlerts.(NGFW)IPS
  description: mapping of scenario to alerts
  type: unknown
- contextPath: 'SummaryAlerts.BenignSecurity '
  description: mapping of scenario to alerts
  type: unknown
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ea7962db-48e7-42d1-8c29-fa6d70a7223d
      iscommand: false
      name: ""
      version: -1
    taskid: ea7962db-48e7-42d1-8c29-fa6d70a7223d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 240,
          "y": 55
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: PaloAltoNetworksXDR.Incident.alerts.host_ip_list
          operator: containsGeneral
          right:
            value:
              simple: 10.1.2.13
      label: BenignScan
    - condition:
      - - left:
            iscontext: true
            value:
              simple: PaloAltoNetworksXDR.Incident.network_artifacts.network_remote_port
          operator: isEqualString
          right:
            value:
              simple: "443"
        - left:
            iscontext: true
            value:
              simple: PaloAltoNetworksXDR.Incident.alerts.host_ip_list
          operator: isEqualString
          right:
            value:
              simple: 10.1.2.13
      label: IPS Alerts
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "11"
      BenignScan:
      - "9"
      IPS Alerts:
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Choose playbook to run by alert category.
      id: 0b89754b-3421-4e2a-8a0a-f77ee84335c2
      iscommand: false
      name: Choose playbook by category
      type: condition
      version: -1
    taskid: 0b89754b-3421-4e2a-8a0a-f77ee84335c2
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 240,
          "y": 240
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1de72c23-6168-4846-8d2e-7b3ac0464f4b
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 1de72c23-6168-4846-8d2e-7b3ac0464f4b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 240,
          "y": 890
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: BenignScan
      value:
        simple: ${inputs.alert}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 38ad7f9a-f412-4013-808d-4da01b7eb157
      iscommand: false
      name: Benign Security Test
      script: Set
      type: regular
      version: -1
    taskid: 38ad7f9a-f412-4013-808d-4da01b7eb157
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -260,
          "y": 495
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: SummaryAlerts.(NGFW)IPS
      value:
        simple: ${inputs.alert}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: a3b9e97f-2781-4e67-8d2c-81ae9488f9e8
      iscommand: false
      name: NGFW Alert IPS
      script: Set
      type: regular
      version: -1
    taskid: a3b9e97f-2781-4e67-8d2c-81ae9488f9e8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 240,
          "y": 495
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: SummaryAlerts.None
      value:
        simple: ${inputs.alert}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 6d6e2c27-7df0-4d6d-89b3-93e063939bd3
      iscommand: false
      name: No match
      script: Set
      type: regular
      version: -1
    taskid: 6d6e2c27-7df0-4d6d-89b3-93e063939bd3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 750,
          "y": 480
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 2
    scriptarguments:
      caseSource:
        simple: Cortex XDR
      caseTitle:
        simple: ${PaloAltoNetworksXDR.Incident.description}  - ${PaloAltoNetworksXDR.Incident.incident_id}
      casecreation_casesource:
        simple: XSOAR_CORTEX_XDR
      casecreation_casetitle:
        simple: ${PaloAltoNetworksXDR.Incident.description}  - ${PaloAltoNetworksXDR.Incident.incident_id}
      casecreation_customerid:
        simple: ${MSSPortal.CustomerInfo.id}
      casecreation_description:
        simple: ${PaloAltoNetworksXDR.Incident.description}
      casecreation_priority:
        simple: ${PaloAltoNetworksXDR.Incident.severity}
      casecreation_servicecomponent:
        simple: SOC
      customerId:
        simple: ${MSSPortal.tsp_customer_id}
      description:
        simple: ${PaloAltoNetworksXDR.Incident.description}
      priority:
        simple: ${PaloAltoNetworksXDR.Incident.severity}
      serviceComponent:
        simple: SOC
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'mssportal-create-case command: Returns a MSSPortal case'
      id: aaa9d88b-6e4d-468a-8836-a790cb86e6a7
      iscommand: true
      name: Create a case in portal
      script: '|||mssportal-create-case'
      type: regular
      version: -1
    taskid: aaa9d88b-6e4d-468a-8836-a790cb86e6a7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 420,
          "y": 1540
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 2
    scriptarguments:
      alertcreation_customerid:
        simple: ${MSSPortal.CaseInfo.customerId}
      alertcreation_name:
        simple: ${MSSPortal.CaseInfo.caseTitle}
      alertcreation_severity:
        simple: ${MSSPortal.CaseInfo.priority}
      alertcreation_sourcealertid:
        simple: ${PaloAltoNetworksXDR.Incident.incident_id}
      alertcreation_sourcecreatedat:
        complex:
          accessor: creation_time
          root: PaloAltoNetworksXDR.Incident
          transformers:
          - operator: TimeStampToDate
      alertcreation_sourceid:
        simple: ${MSSPortal.CaseInfo.caseSource}
      alertcreation_sourcemodifiedat:
        complex:
          accessor: modification_time
          root: PaloAltoNetworksXDR.Incident
          transformers:
          - operator: TimeStampToDate
      caseDescription:
        simple: ${MSSPortal.Case.description}
      caseTitle:
        simple: ${MSSPortal.Case.caseTitle}
      customerId:
        simple: ${MSSPortal.Case.customerId}
      investigationCaseId:
        simple: ${MSSPortal.Case.id}
      name:
        simple: ${MSSPortal.Case.caseTitle}
      severity:
        simple: ${MSSPortal.Case.priority}
      sourceAlertId:
        simple: ${PaloAltoNetworksXDR.Incident.incident_id}
      sourceCreatedAt:
        complex:
          accessor: creation_time
          root: PaloAltoNetworksXDR.Incident
          transformers:
          - operator: TimeStampToDate
      sourceId:
        simple: ${MSSPortal.Case.caseSource}
      sourceModifiedAt:
        complex:
          accessor: modification_time
          root: PaloAltoNetworksXDR.Incident
          transformers:
          - operator: TimeStampToDate
      sourceRaw:
        simple: ${PaloAltoNetworksXDR.Incident}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'mssportal-create-alert command: Returns a MSSPortal alert'
      id: 2243fdcc-7e9a-4d5e-8591-20e1f0e19c8f
      iscommand: true
      name: Create an alert to the case
      script: '|||mssportal-create-alert'
      type: regular
      version: -1
    taskid: 2243fdcc-7e9a-4d5e-8591-20e1f0e19c8f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 420,
          "y": 1715
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 2
    scriptarguments:
      caseSource:
        simple: Cortex XDR
      caseTitle:
        simple: ${PaloAltoNetworksXDR.Incident.description}  - ${PaloAltoNetworksXDR.Incident.incident_id}
      casecreation_casesource:
        simple: XSOAR_CORTEX_XDR
      casecreation_casetitle:
        simple: ${PaloAltoNetworksXDR.Incident.description}  - ${PaloAltoNetworksXDR.Incident.incident_id}
      casecreation_customerid:
        simple: ${MSSPortal.CustomerInfo.id}
      casecreation_description:
        simple: ${PaloAltoNetworksXDR.Incident.description}
      casecreation_priority:
        simple: ${PaloAltoNetworksXDR.Incident.severity}
      casecreation_servicecomponent:
        simple: SOC
      customerId:
        simple: ${MSSPortal.tsp_customer_id}
      description:
        simple: ${PaloAltoNetworksXDR.Incident.description}
      priority:
        simple: ${PaloAltoNetworksXDR.Incident.severity}
      serviceComponent:
        simple: SOC
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'mssportal-create-case command: Returns a MSSPortal case'
      id: b54552e1-8d05-4622-8ec5-a2e29062d4b3
      iscommand: true
      name: Create a case in portal
      script: '|||mssportal-create-case'
      type: regular
      version: -1
    taskid: b54552e1-8d05-4622-8ec5-a2e29062d4b3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 420,
          "y": 1540
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 2
    scriptarguments:
      alertcreation_customerid:
        simple: ${MSSPortal.CaseInfo.customerId}
      alertcreation_name:
        simple: ${MSSPortal.CaseInfo.caseTitle}
      alertcreation_severity:
        simple: ${MSSPortal.CaseInfo.priority}
      alertcreation_sourcealertid:
        simple: ${PaloAltoNetworksXDR.Incident.incident_id}
      alertcreation_sourcecreatedat:
        complex:
          accessor: creation_time
          root: PaloAltoNetworksXDR.Incident
          transformers:
          - operator: TimeStampToDate
      alertcreation_sourceid:
        simple: ${MSSPortal.CaseInfo.caseSource}
      alertcreation_sourcemodifiedat:
        complex:
          accessor: modification_time
          root: PaloAltoNetworksXDR.Incident
          transformers:
          - operator: TimeStampToDate
      caseDescription:
        simple: ${MSSPortal.Case.description}
      caseTitle:
        simple: ${MSSPortal.Case.caseTitle}
      customerId:
        simple: ${MSSPortal.Case.customerId}
      investigationCaseId:
        simple: ${MSSPortal.Case.id}
      name:
        simple: ${MSSPortal.Case.caseTitle}
      severity:
        simple: ${MSSPortal.Case.priority}
      sourceAlertId:
        simple: ${PaloAltoNetworksXDR.Incident.incident_id}
      sourceCreatedAt:
        complex:
          accessor: creation_time
          root: PaloAltoNetworksXDR.Incident
          transformers:
          - operator: TimeStampToDate
      sourceId:
        simple: ${MSSPortal.Case.caseSource}
      sourceModifiedAt:
        complex:
          accessor: modification_time
          root: PaloAltoNetworksXDR.Incident
          transformers:
          - operator: TimeStampToDate
      sourceRaw:
        simple: ${PaloAltoNetworksXDR.Incident}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'mssportal-create-alert command: Returns a MSSPortal alert'
      id: 0bc4f831-8105-407e-8692-093eaeee9c9c
      iscommand: true
      name: Create an alert to the case
      script: '|||mssportal-create-alert'
      type: regular
      version: -1
    taskid: 0bc4f831-8105-407e-8692-093eaeee9c9c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 420,
          "y": 1715
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1755,
        "width": 1390,
        "x": -260,
        "y": 55
      }
    }
  }
